// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-31-2018
// ***********************************************************************
// <copyright file="FtpDirListEventHandler.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;


namespace TelEnvyCOMLibrary.Handlers
{
    /// <summary>
    /// Delegate FtpDirListEventHandler
    /// </summary>
    /// <param name="sender">The sender.</param>
    /// <param name="ea">The ea.</param>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FtpDirListEventHandler
    public delegate void FtpDirListEventHandler(object sender, nsoftware.IPWorks.Ftp.OnDirListHandler ea);
}
