// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-27-2018
// ***********************************************************************
// <copyright file="FtpEndTransferHandler.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using TelEnvyCOMLibrary.EventArgs;

namespace TelEnvyCOMLibrary.Handlers
{
    /// <summary>
    /// Delegate FtpEndTransferHandler
    /// </summary>
    /// <param name="sender">The sender.</param>
    /// <param name="ea">The <see cref="FtpEndTransferCOMEventArgs"/> instance containing the event data.</param>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FtpEndTransferHandler
    public delegate void FtpEndTransferHandler(object sender, FtpEndTransferCOMEventArgs ea);
}
