// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-27-2018
// ***********************************************************************
// <copyright file="FtpPITrailEventHandler.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using nsoftware.IPWorks;
using System;
using System.Collections.Generic;
using System.Linq;
using TelEnvyCOMLibrary.EventArgs;

namespace TelEnvyCOMLibrary.Handlers
{
    /// <summary>
    /// Delegate FtpPITrailEventHandler
    /// </summary>
    /// <param name="sender">The sender.</param>
    /// <param name="ea">The <see cref="FtpPITrailCOMEventArgs"/> instance containing the event data.</param>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FtpPITrailEventHandler
    public delegate void FtpPITrailEventHandler(object sender, FtpPITrailCOMEventArgs ea);
}
