// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-27-2018
// ***********************************************************************
// <copyright file="FtpTransferEventHandler.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using nsoftware.IPWorks;
using System;
using System.Collections.Generic;
using System.Linq;

namespace TelEnvyCOMLibrary.Handlers
{
    /// <summary>
    /// Delegate FtpTransferEventHandler
    /// </summary>
    /// <param name="sender">The sender.</param>
    /// <param name="e">The <see cref="FtpTransferEventArgs"/> instance containing the event data.</param>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FtpTransferEventHandler
    public delegate void FtpTransferEventHandler(object sender, FtpTransferEventArgs e);
}
