// ***********************************************************************
// Assembly         : TeLXmlLib
// Author           : Timothy Peer
// Created          : 01-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 02-24-2018
// ***********************************************************************
// <copyright file="AndCondition.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Xml;
using TelEnvyXmlLib.Enums;


namespace TelEnvyXmlLib.Conditions
{
    #region Documentation
    /// Class AndCondition.
    ///
    /// \author Timothy Peer, eNVy Systems Inc.
    /// \date   6/26/2019
    ///
    /// \sa TelEnvyXmlLib.Conditions.LogicalCondition
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for AndCondition //
    #endregion

    ///-------------------------------------------------------------------------------------------------
    /// <summary>   An and condition. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///
    /// <seealso cref="T:TelEnvyXmlLib.Conditions.LogicalCondition"/>
    ///-------------------------------------------------------------------------------------------------

    public class AndCondition : LogicalCondition
    {
        #region Documentation
        /// Initializes a new instance of the <see cref="AndCondition" /> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \exception  TeLInvalidDataFormatException   Thrown when a Te L Invalid Data Format error
        ///                                             condition occurs.
        ///
        /// \param  node    The node.
        ///
        /// ### exception   TelEnvyXmlLib.Exceptions.TeLInvalidDataFormatException  .
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Conditions.AndCondition class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <exception cref="TeLInvalidDataFormatException"> Thrown when a Te L Invalid Data Format error
        ///                                                  condition occurs.</exception>
        ///
        /// <param name="node"> The node.</param>
        ///-------------------------------------------------------------------------------------------------

        public AndCondition(XmlNode node)
            : base(node, TelEnvyXmlLib.Enums.IfConditionType.And)
        {
            if (ChildConditions.Count < 2)
                throw new TelEnvyXmlLib.Exceptions.TeLInvalidDataFormatException(string.Format("<IfCondition Type=\"{0}\"> requires at least two child nodes of type <IfCondition>.", ConditionType));
        }

        #region Documentation
        /// Initializes a new instance of the <see cref="AndCondition"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  node    The node.
        /// \param  type    The type.
        ///
        /// ### exception   TelEnvyXmlLib.Exceptions.TeLInvalidDataFormatException  .
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Conditions.AndCondition class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="node"> The node.</param>
        /// <param name="type"> The type.</param>
        ///-------------------------------------------------------------------------------------------------

        public AndCondition(XmlNode node, TelEnvyXmlLib.Enums.IfConditionType type)
            : base(node, type)
        {
            
        }

    }
}
