// ***********************************************************************
// Assembly         : TeLXmlLib
// Author           : tim
// Created          : 01-25-2018
//
// Last Modified By : tim
// Last Modified On : 02-05-2018
// ***********************************************************************
// <copyright file="EmptyCondition.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Xml;

namespace TelEnvyXmlLib.Conditions
{
    #region Documentation
    /// Class EmptyCondition.
    ///
    /// \author Timothy Peer, eNVy Systems Inc.
    /// \date   6/26/2019
    ///
    /// \sa TelEnvyXmlLib.Conditions.FinalCondition
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for EmptyCondition //
    #endregion

    ///-------------------------------------------------------------------------------------------------
    /// <summary>   An empty condition. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///
    /// <seealso cref="T:TelEnvyXmlLib.Conditions.FinalCondition"/>
    ///-------------------------------------------------------------------------------------------------

    public class EmptyCondition : FinalCondition
    {
        #region Documentation
        /// Initializes a new instance of the <see cref="EmptyCondition" /> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  node    The node.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Conditions.EmptyCondition class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="node"> The node.</param>
        ///-------------------------------------------------------------------------------------------------

        public EmptyCondition(XmlNode node) : base(node, TelEnvyXmlLib.Enums.IfConditionType.EmptyIfCondition) { }
    }
}
