// ***********************************************************************
// Assembly         : TeLXmlLib
// Author           : tim
// Created          : 01-25-2018
//
// Last Modified By : tim
// Last Modified On : 01-31-2018
// ***********************************************************************
// <copyright file="FinalCondition.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Xml;

namespace TelEnvyXmlLib.Conditions
{
    #region Documentation
    /// Class FinalCondition.
    ///
    /// \author Timothy Peer, eNVy Systems Inc.
    /// \date   6/26/2019
    ///
    /// \sa TelEnvyXmlLib.Conditions.ConditionBase
    /// <autogeneratedoc />
    /// //
    #endregion

    ///-------------------------------------------------------------------------------------------------
    /// <summary>   A final condition. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///
    /// <seealso cref="T:TelEnvyXmlLib.Conditions.ConditionBase"/>
    ///-------------------------------------------------------------------------------------------------

    public class FinalCondition : ConditionBase
    {
        /// <summary>   The nodes. </summary>
        List<TelEnvyXmlLib.Abstract.TeLSessionNode> _nodes; /* The nodes */

        #region Documentation
        /// Gets the condition nodes.
        ///
        /// \returns    The condition nodes.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets the condition nodes. </summary>
        ///
        /// <value> The condition nodes. </value>
        ///
        /// <seealso cref="P:TelEnvyXmlLib.Conditions.ConditionBase.ConditionNodes"/>
        ///-------------------------------------------------------------------------------------------------

        public override List<TelEnvyXmlLib.Abstract.TeLSessionNode> ConditionNodes
        {
            get { return _nodes; }
        }

        #region Documentation
        /// Initializes a new instance of the <see cref="FinalCondition" /> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  node    The node.
        /// \param  type    The type.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Conditions.FinalCondition class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="node"> The node.</param>
        /// <param name="type"> The type.</param>
        ///-------------------------------------------------------------------------------------------------

        public FinalCondition(XmlNode node, TelEnvyXmlLib.Enums.IfConditionType type)
            : base(node, type)
        {
            _nodes = new List<TelEnvyXmlLib.Abstract.TeLSessionNode>();

            int i = 0;
            for (XmlNode child =TelEnvyXmlLib.Helper.TeLSessionXmlParser.ReadNextChildElement(node, ref i); child != null; child = TelEnvyXmlLib.Helper.TeLSessionXmlParser.ReadNextChildElement(node, ref i))
            {
                _nodes.Add(TelEnvyXmlLib.Helper.TeLSessionXmlParser.Parse(child));
            }
        }
    }
}
