//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CCRt.Module.BusinessObjects.Database
{

    public partial class SyCmdClass : XPCustomObject
    {
        Guid fPkId;
        [Key(true)]
        public Guid PkId
        {
            get { return fPkId; }
            set { SetPropertyValue<Guid>(nameof(PkId), ref fPkId, value); }
        }
        string fCmdName;
        public string CmdName
        {
            get { return fCmdName; }
            set { SetPropertyValue<string>(nameof(CmdName), ref fCmdName, value); }
        }
        string fCmdDescription;
        public string CmdDescription
        {
            get { return fCmdDescription; }
            set { SetPropertyValue<string>(nameof(CmdDescription), ref fCmdDescription, value); }
        }
        Guid fBatchIPkd;
        [Indexed(Name = @"iBatchIPkd_SyCmdClass")]
        public Guid BatchIPkd
        {
            get { return fBatchIPkd; }
            set { SetPropertyValue<Guid>(nameof(BatchIPkd), ref fBatchIPkd, value); }
        }
        Guid fBatchId;
        [Indexed(Name = @"iBatchId_SyCmdClass")]
        public Guid BatchId
        {
            get { return fBatchId; }
            set { SetPropertyValue<Guid>(nameof(BatchId), ref fBatchId, value); }
        }
        int fMaxChildRows;
        public int MaxChildRows
        {
            get { return fMaxChildRows; }
            set { SetPropertyValue<int>(nameof(MaxChildRows), ref fMaxChildRows, value); }
        }
        double fSequence;
        public double Sequence
        {
            get { return fSequence; }
            set { SetPropertyValue<double>(nameof(Sequence), ref fSequence, value); }
        }
        bool fIsClone;
        public bool IsClone
        {
            get { return fIsClone; }
            set { SetPropertyValue<bool>(nameof(IsClone), ref fIsClone, value); }
        }
        bool fAccountDescrip;
        public bool AccountDescrip
        {
            get { return fAccountDescrip; }
            set { SetPropertyValue<bool>(nameof(AccountDescrip), ref fAccountDescrip, value); }
        }
        string fListOfPartNumbers;
        public string ListOfPartNumbers
        {
            get { return fListOfPartNumbers; }
            set { SetPropertyValue<string>(nameof(ListOfPartNumbers), ref fListOfPartNumbers, value); }
        }
        string fListOfAccounts;
        public string ListOfAccounts
        {
            get { return fListOfAccounts; }
            set { SetPropertyValue<string>(nameof(ListOfAccounts), ref fListOfAccounts, value); }
        }
        string fListOfWarehouses;
        public string ListOfWarehouses
        {
            get { return fListOfWarehouses; }
            set { SetPropertyValue<string>(nameof(ListOfWarehouses), ref fListOfWarehouses, value); }
        }
        string fAdjustmentAccountNumber;
        public string AdjustmentAccountNumber
        {
            get { return fAdjustmentAccountNumber; }
            set { SetPropertyValue<string>(nameof(AdjustmentAccountNumber), ref fAdjustmentAccountNumber, value); }
        }
        string fListOfPlantCode;
        public string ListOfPlantCode
        {
            get { return fListOfPlantCode; }
            set { SetPropertyValue<string>(nameof(ListOfPlantCode), ref fListOfPlantCode, value); }
        }
        MgAccountNumbers ffkAccountNumber;
        [Association(@"SyCmdClassReferencesMgAccountNumbers")]
        public MgAccountNumbers fkAccountNumber
        {
            get { return ffkAccountNumber; }
            set { SetPropertyValue<MgAccountNumbers>(nameof(fkAccountNumber), ref ffkAccountNumber, value); }
        }
        MgPartMaster ffkPartNumber;
        [Association(@"SyCmdClassReferencesMgPartMaster")]
        public MgPartMaster fkPartNumber
        {
            get { return ffkPartNumber; }
            set { SetPropertyValue<MgPartMaster>(nameof(fkPartNumber), ref ffkPartNumber, value); }
        }
        MgWarehouseMaster ffkWarehouseCode;
        [Association(@"SyCmdClassReferencesMgWarehouseMaster")]
        public MgWarehouseMaster fkWarehouseCode
        {
            get { return ffkWarehouseCode; }
            set { SetPropertyValue<MgWarehouseMaster>(nameof(fkWarehouseCode), ref ffkWarehouseCode, value); }
        }
    }

}
