// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-27-2018
// ***********************************************************************
// <copyright file="FtpErrorCOMEventArgs.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;

namespace TelEnvyCOMLibrary.EventArgs
{
    /// <summary>
    /// Class FtpErrorCOMEventArgs.
    /// </summary>
    /// <seealso cref="System.EventArgs" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FtpErrorCOMEventArgs
    public class FtpErrorCOMEventArgs : System.EventArgs
    {
        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        /// <value>The description.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Description
        public string Description { get; set; }
        /// <summary>
        /// Gets or sets the error code.
        /// </summary>
        /// <value>The error code.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ErrorCode
        public int ErrorCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FtpErrorCOMEventArgs" /> class.
        /// </summary>
        /// <param name="description">The description.</param>
        /// <param name="errorCode">The error code.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public FtpErrorCOMEventArgs(string description, int errorCode)
        {
            Description = description;
            ErrorCode = errorCode;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FtpErrorCOMEventArgs" /> class.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public FtpErrorCOMEventArgs()
        {
            
        }

    }
}
