// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-27-2018
// ***********************************************************************
// <copyright file="FtpTransferCOMEventArgs.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;

namespace TelEnvyCOMLibrary.EventArgs
{
    //
    // Summary:
    //     Event arguments for the Transfer event.
    /// <summary>
    /// Class FtpTransferCOMEventArgs.
    /// </summary>
    /// <seealso cref="System.EventArgs" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FtpTransferCOMEventArgs
    public class FtpTransferCOMEventArgs : System.EventArgs
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="FtpTransferCOMEventArgs" /> class.
        /// </summary>
        /// <param name="bytesTransferred">The bytes transferred.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="percentDone">The percent done.</param>
        /// <param name="text">The text.</param>
        /// <param name="textB">The text b.</param>
        public FtpTransferCOMEventArgs(long bytesTransferred, int direction, int percentDone, string text, byte[] textB)
        {
            BytesTransferred = bytesTransferred;
            Direction = direction;
            PercentDone = percentDone;
            Text = text;
            TextB = textB;
        }
        /// <summary>
        /// Gets or sets the bytes transferred.
        /// </summary>
        /// <value>The bytes transferred.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for BytesTransferred
        public long BytesTransferred { get; set; }
        /// <summary>
        /// Gets or sets the direction.
        /// </summary>
        /// <value>The direction.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Direction
        public int Direction { get; set; }
        /// <summary>
        /// Gets or sets the percent done.
        /// </summary>
        /// <value>The percent done.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for PercentDone
        public int PercentDone { get; set; }
        /// <summary>
        /// Gets or sets the text.
        /// </summary>
        /// <value>The text.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Text
        public string Text { get; set; }
        /// <summary>
        /// Gets or sets the text b.
        /// </summary>
        /// <value>The text b.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TextB
        public byte[] TextB { get; set; }
    }
}
