// ***********************************************************************
// Assembly         : TelEnvyXmlLib
// Author           : Timothy Peer
// Created          : 02-24-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 02-24-2018
// ***********************************************************************
// <copyright file="EnumLoggingOptions.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Linq;

namespace TelEnvyXmlLib.Enums
{
    ///-------------------------------------------------------------------------------------------------
    /// <summary>   Enum EnumLoggingOptions. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///-------------------------------------------------------------------------------------------------

    public enum EnumLoggingOptions
    {
        /// <summary>
        /// The unique identifier
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GUID
        GUID = 0,   /* An enum constant representing the Unique identifier option */
        /// <summary>
        /// The long time stamp
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LongTimeStamp
        LongTimeStamp,  /* An enum constant representing the long time stamp option */
        /// <summary>
        /// The daily incrementer
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DailyIncrementer
        DailyIncrementer    /* An enum constant representing the daily incrementer option */
    }
}
