// ***********************************************************************
// Assembly         : TelEnvyXmlLib
// Author           : Timothy Peer
// Created          : 04-16-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 04-16-2018
// ***********************************************************************
// <copyright file="TransferModes.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Linq;


namespace TelEnvyXmlLib.Enums
{
    ///-------------------------------------------------------------------------------------------------
    /// <summary>   Enum TransferModes. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///-------------------------------------------------------------------------------------------------

    public enum FtpTransferModes
    {
        /// <summary>
        /// The tm default
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for tmDefault
        tmDefault = 0,  /* An enum constant representing the Time default option */
        /// <summary>
        /// The tm ASCII
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for tmASCII
        tmASCII = 1,    /* An enum constant representing the Time a scii option */
        /// <summary>
        /// The tm binary
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for tmBinary
        tmBinary = 2    /* An enum constant representing the Time binary option */
    }
}
