// ***********************************************************************
// Assembly         : TeLXmlLib
// Author           : Timothy Peer
// Created          : 01-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 01-27-2018
// ***********************************************************************
// <copyright file="IfConditionType.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Linq;

namespace TelEnvyXmlLib.Enums
{
    ///-------------------------------------------------------------------------------------------------
    /// <summary>   Enum IfConditionType. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///-------------------------------------------------------------------------------------------------

    public enum IfConditionType
    {
        // <IfCondition Type="EmptyIfCondition">
        /// <summary>
        /// The empty if condition
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for EmptyIfCondition
        EmptyIfCondition,   /* An enum constant representing the empty if condition option */

        // <IfCondition Type="CursorAtPosition" Row="1" Column="3">
        /// <summary>
        /// The cursor at position
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for CursorAtPosition
        CursorAtPosition,   /* An enum constant representing the cursor at position option */

        // <IfCondition Type="CursorWithinRegion" Row="1" Column="3" Width="5" Height="3">
        /// <summary>
        /// The cursor within region
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for CursorWithinRegion
        CursorWithinRegion, /* An enum constant representing the cursor within region option */

        // <IfCondition Type="DataAtCursorPosition" Data="Delete?"> 
        /// <summary>
        /// The data at cursor position
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DataAtCursorPosition
        DataAtCursorPosition,   /* An enum constant representing the data at cursor position option */

        // <IfCondition Type="DataBeforeCursorPosition" Data="Delete?"> 
        /// <summary>
        /// The data before cursor position
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DataBeforeCursorPosition
        DataBeforeCursorPosition,   /* An enum constant representing the data before cursor position option */

        // <IfCondition Type="DataWithinRegion" Row="1" Column="3" Width="5" Height="3" Data="Delete?">
        // <IfCondition Type="DataWithinRegion" Row="0" Column="-10" Width="10" Height="1" Data="Delete?" RelativeToCursor="true">
        /// <summary>
        /// The data within region
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DataWithinRegion
        DataWithinRegion,   /* An enum constant representing the data within region option */

        // <IfCondition Type="Not">
        /// <summary>
        /// The not
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Not
        Not,    /* An enum constant representing the not option */

        // <IfCondition Type="And">
        /// <summary>
        /// The and
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for And
        And,    /* An enum constant representing the and option */

        // <IfCondition Type="Or">
        /// <summary>
        /// The or
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Or
        Or, /* An enum constant representing the or option */
    }
}
