//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CCRt.Module.BusinessObjects
{

    public partial class MgAccounts : SyCustomBase
    {
        Guid fOid;
        [Key(true)]
        [Browsable(false)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fAccountNumber;
        [Browsable(true)]
        public string AccountNumber
        {
            get { return fAccountNumber; }
            set { SetPropertyValue<string>(nameof(AccountNumber), ref fAccountNumber, value); }
        }

        SyBatch ffkAccountNumber;
        [Browsable(false)]
        [Association(@"SyBatchReferencesMgAccountNumbers")]
        public SyBatch fkAccountNumber
        {
            get { return ffkAccountNumber; }
            set { SetPropertyValue<SyBatch>(nameof(fkAccountNumber), ref ffkAccountNumber, value); }
        }

    }

}
