//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp.DC;

namespace CCRt.Module.BusinessObjects
{

    public partial class MgPartMaster : SyCustomBase
    {
        Guid fOid;
        [Key(true)]
        [Browsable(false)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fPartNumber_Assy;
        private string fPartNumber_Component;
        [Browsable(true)]
        [Size(SizeAttribute.Unlimited)]
        [XafDisplayName("Assembly Parts")]
        public string Assemply_Parts
        {
            get { return fPartNumber_Assy; }
            set { SetPropertyValue<string>(nameof(Assemply_Parts), ref fPartNumber_Assy, value); }
        }
        [Browsable(true)]
        [Size(SizeAttribute.Unlimited)]
        [XafDisplayName("Component Parts")]
        public string Component_Parts
        {
            get { return fPartNumber_Component; }
            set { SetPropertyValue<string>(nameof(Component_Parts), ref fPartNumber_Component, value); }
        }

        SyBatch ffkPartNumber;
        [Browsable(false)]
        [Association(@"SyBatchReferencesMgPartMaster")]
        public SyBatch fkPartNumber
        {
            get { return ffkPartNumber; }
            set { SetPropertyValue<SyBatch>(nameof(fkPartNumber), ref ffkPartNumber, value); }
        }
    }

}
