//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CCRt.Module.BusinessObjects
{
   
    public partial class MgWarehouseMaster : SyCustomBase
    {
        Guid fOid;
        [Key(true)]
        [Browsable(false)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fWarehouseCode;
        [Browsable(true)]
        public string WarehouseCode
        {
            get { return fWarehouseCode; }
            set { SetPropertyValue<string>(nameof(WarehouseCode), ref fWarehouseCode, value); }
        }


        SyBatch fkWarehouse_Code;
        [Browsable(false)]
        [Association(@"SyBatchReferencesMgWarehouseMaster")]
        public SyBatch fk_WarehouseCode
        {
            get { return fkWarehouse_Code; }
            set { SetPropertyValue<SyBatch>(nameof(fk_WarehouseCode), ref fkWarehouse_Code, value); }
        }
    }

}
