// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-27-2018
// ***********************************************************************
// <copyright file="DirEntryClass.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TelEnvyCOMLibrary
{
    /// <summary>
    /// Class DirEntryClass.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for DirEntryClass
    public class DirEntryClass 
    {
        // Fields...

        /// <summary>
        /// Gets or sets the entry.
        /// </summary>
        /// <value>The entry.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Entry
        public string Entry { get; set; }

        /// <summary>
        /// Gets or sets the name of the file.
        /// </summary>
        /// <value>The name of the file.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for FileName
        public string FileName { get; set; }

        /// <summary>
        /// Gets or sets the size of the file.
        /// </summary>
        /// <value>The size of the file.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for FileSize
        public long FileSize { get; set; }

        /// <summary>
        /// Gets or sets the file time.
        /// </summary>
        /// <value>The file time.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for FileTime
        public string FileTime { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is dir.
        /// </summary>
        /// <value><c>true</c> if this instance is dir; otherwise, <c>false</c>.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for IsDir
        public bool IsDir { get; set; }




    }
}
