// ***********************************************************************
// Assembly         : TelEnvyXmlLib
// Author           : Timothy Peer
// Created          : 02-24-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 02-24-2018
// ***********************************************************************
// <copyright file="TelLogWriterEventArg.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Linq;



namespace TelEnvyXmlLib.EventArgs
{
    #region Documentation
    /// Class TelLogWriterEventArg.
    ///
    /// \author Timothy Peer, eNVy Systems Inc.
    /// \date   6/26/2019
    ///
    /// \sa System.EventArgs        
    /// \sa TelEnvyXmlLib.EventArgs <autogeneratedoc />
    ///                             TODO Edit XML Comment Template for TelLogWriterEventArg
    #endregion

    ///-------------------------------------------------------------------------------------------------
    /// <summary>   A tel log writer event argument. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///
    /// <seealso cref="T:System.EventArgs"/>
    ///-------------------------------------------------------------------------------------------------

    public class TelLogWriterEventArg : System.EventArgs
    {
        #region Documentation
        /// Initializes a new instance of the <see cref="TelLogWriterEventArg"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  receivedData    The received data.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.EventArgs.TelLogWriterEventArg
        ///             class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="receivedData"> Information describing the received.</param>
        ///-------------------------------------------------------------------------------------------------

        public TelLogWriterEventArg(string receivedData)
        {
            LogData = receivedData;
        }

        #region Documentation
        /// Initializes a new instance of the <see cref="TelLogWriterEventArg"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.EventArgs.TelLogWriterEventArg
        ///             class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///-------------------------------------------------------------------------------------------------

        public TelLogWriterEventArg()
        {

        }

        #region Documentation
        /// Gets or sets the log data.
        ///
        /// \returns    The log data.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets or sets information describing the log. </summary>
        ///
        /// <value> Information describing the log. </value>
        ///-------------------------------------------------------------------------------------------------

        public string LogData { get; set; }

        #region Documentation
        /// Gets or sets a value indicating whether [to console].
        ///
        /// \returns    <c>true</c> if [to console]; otherwise, <c>false</c>.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets or sets a value indicating whether to console. </summary>
        ///
        /// <value> True if to console, false if not. </value>
        ///-------------------------------------------------------------------------------------------------

        public bool ToConsole { get; set; }
    }
}
