// ***********************************************************************
// Assembly         : TeLXmlLib
// Author           : tim
// Created          : 01-03-2018
//
// Last Modified By : Timothy Peer, eNVy Systems Inc.
// Last Modified On : 01-31-2018
// ***********************************************************************
// <copyright file="TeLSessionNodeProcessEventArg.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;


namespace TelEnvyXmlLib.EventArgs
{
    #region Documentation
    /// Class TeLSessionNodeProcessEventArg.
    ///
    /// \author Timothy Peer, eNVy Systems Inc.
    /// \date   6/26/2019
    ///
    /// \sa System.EventArgs
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for TeLSessionNodeProcessEventArg
    #endregion

    ///-------------------------------------------------------------------------------------------------
    /// <summary>   A te l session node process event argument. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///
    /// <seealso cref="T:System.EventArgs"/>
    ///-------------------------------------------------------------------------------------------------

    public class TeLSessionNodeProcessEventArg : System.EventArgs
	{
        #region Documentation
        /// Gets or sets the node.
        ///
        /// \returns    The node.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets the node. </summary>
        ///
        /// <value> The node. </value>
        ///-------------------------------------------------------------------------------------------------

        public TelEnvyXmlLib.Abstract.TeLSessionNode Node { get; private set; }

        #region Documentation
        /// Gets or sets the level.
        ///
        /// \returns    The level.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets the level. </summary>
        ///
        /// <value> The level. </value>
        ///-------------------------------------------------------------------------------------------------

        public int Level { get; private set; }

        #region Documentation
        /// Gets or sets the name of the module log
        ///
        /// \returns    The name of the module log.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets or sets the name of the module log. </summary>
        ///
        /// <value> The name of the module log. </value>
        ///-------------------------------------------------------------------------------------------------

        public string ModuleLogName { get; set; }

        #region Documentation
        /// Initializes a new instance of the <see cref="TeLSessionNodeProcessEventArg" /> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  node            The node.
        /// \param  level           The level.
        /// \param  moduleLogName   Name of the module log.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the
        ///             TelEnvyXmlLib.EventArgs.TeLSessionNodeProcessEventArg class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="node">             The node.</param>
        /// <param name="level">            The level.</param>
        /// <param name="moduleLogName">    Name of the module log.</param>
        ///-------------------------------------------------------------------------------------------------

        public TeLSessionNodeProcessEventArg(Abstract.TeLSessionNode node, int level, string moduleLogName)
		{
			Node = node;
			Level = level;
            ModuleLogName = moduleLogName;
            StaticLogger.LogTrace(ModuleLogName, string.Format("Node {0} : Level {1}", Node,level));
        }

        #region Documentation
        /// Default constructor
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the
        ///             TelEnvyXmlLib.EventArgs.TeLSessionNodeProcessEventArg class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///-------------------------------------------------------------------------------------------------

        public TeLSessionNodeProcessEventArg()
        {
            
        }

    }
}
