// ***********************************************************************
// Assembly         : TeLXmlLib
// Author           : tim
// Created          : 01-25-2018
//
// Last Modified By : Timothy Peer, eNVy Systems Inc.
// Last Modified On : 01-31-2018
// ***********************************************************************
// <copyright file="TeLSessionNodeCancelEventArg.cs" company="eNVy Systems, Inc.">
//     Copyright © eNVy Systems, Inc. 2011
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Linq;



namespace TelEnvyXmlLib.EventArgs
{
    #region Documentation
    /// Class TeLSessionNodeCancelEventArg.
    ///
    /// \author Timothy Peer, eNVy Systems Inc.
    /// \date   6/26/2019
    ///
    /// \sa System.EventArgs
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for TeLSessionNodeCancelEventArg
    #endregion

    ///-------------------------------------------------------------------------------------------------
    /// <summary>   A te l session node cancel event argument. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///
    /// <seealso cref="T:System.EventArgs"/>
    ///-------------------------------------------------------------------------------------------------

    public class TeLSessionNodeCancelEventArg : System.EventArgs
    {
        #region Documentation
        /// Gets or sets the node.
        ///
        /// \returns    The node.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets the node. </summary>
        ///
        /// <value> The node. </value>
        ///-------------------------------------------------------------------------------------------------

        public TelEnvyXmlLib.Abstract.TeLSessionNode Node { get; private set; }

        #region Documentation
        /// Gets or sets the level.
        ///
        /// \returns    The level.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets the level. </summary>
        ///
        /// <value> The level. </value>
        ///-------------------------------------------------------------------------------------------------

        public int Level { get; private set; }

        #region Documentation
        /// Initializes a new instance of the <see cref="TeLSessionNodeCancelEventArg" /> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  node    The node.
        /// \param  level   The level.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the
        ///             TelEnvyXmlLib.EventArgs.TeLSessionNodeCancelEventArg class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="node">     The node.</param>
        /// <param name="level">    The level.</param>
        ///-------------------------------------------------------------------------------------------------

        public TeLSessionNodeCancelEventArg(Abstract.TeLSessionNode node, int level)
        {
            Node = node;
            Level = level;
        }
    }
}
