// ***********************************************************************
// Assembly         : PZLib
// Author           : Timothy Peer
// Created          : 02-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 02-27-2018
// ***********************************************************************
// <copyright file="TelEnvyExceptionBase.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.Serialization;
using TelEnvyXmlLib.Helper;

namespace TelEnvyXmlLib.Exceptions
{
    #region Documentation
    /// Class TelEnvyExceptionBase.
    ///
    /// \author Timothy Peer, eNVy Systems Inc.
    /// \date   6/26/2019
    ///
    /// \sa System.Exception
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for TelEnvyExceptionBase
    #endregion

    ///-------------------------------------------------------------------------------------------------
    /// <summary>   A tel envy exception base. </summary>
    ///
    /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
    ///
    /// <seealso cref="T:System.Exception"/>
    ///-------------------------------------------------------------------------------------------------

    public class TelEnvyExceptionBase : Exception
    {
        #region Documentation
        /// Initializes a new instance of the <see cref="TelEnvyExceptionBase"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Exceptions.TelEnvyExceptionBase
        ///             class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///-------------------------------------------------------------------------------------------------

        public TelEnvyExceptionBase()
        {

        }

        #region Documentation
        /// Initializes a new instance of the <see cref="TelEnvyExceptionBase"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  message The message that describes the error.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Exceptions.TelEnvyExceptionBase
        ///             class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="message">  The message.</param>
        ///-------------------------------------------------------------------------------------------------

        public TelEnvyExceptionBase(MessageDetails_c message)
            : base(message.ToString())
        {
            //  UpdateMessage(message);
        }

        #region Documentation
        /// Initializes a new instance of the <see cref="TelEnvyExceptionBase"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  message         The error message that explains the reason for the exception.
        /// \param  innerException  The exception that is the cause of the current exception, or a null
        ///                         reference (Nothing in Visual Basic) if no inner exception is
        ///                         specified.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Exceptions.TelEnvyExceptionBase
        ///             class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="message">          The message.</param>
        /// <param name="innerException">   The inner exception.</param>
        ///-------------------------------------------------------------------------------------------------

        public TelEnvyExceptionBase(MessageDetails_c message, Exception innerException)
            : base(message.ToString(), innerException)
        {
            //  UpdateMessage(message);
        }

        #region Documentation
        /// Initializes a new instance of the <see cref="TelEnvyExceptionBase"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  info    The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that
        ///                 holds the serialized object data about the exception being thrown.
        /// \param  context The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that
        ///                 contains contextual information about the source or destination.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Exceptions.TelEnvyExceptionBase
        ///             class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="info">     The information.</param>
        /// <param name="context">  The context.</param>
        ///-------------------------------------------------------------------------------------------------

        protected TelEnvyExceptionBase(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {

        }

        #region Documentation
        /// Initializes a new instance of the <see cref="TelEnvyExceptionBase"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  message The message that describes the error.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Exceptions.TelEnvyExceptionBase
        ///             class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="message">  The message.</param>
        ///-------------------------------------------------------------------------------------------------

        public TelEnvyExceptionBase(string message)
            : base(message)
        {
            
        }

        #region Documentation
        /// Initializes a new instance of the <see cref="TelEnvyExceptionBase"/> class.
        ///
        /// \author Timothy Peer, eNVy Systems Inc.
        /// \date   6/26/2019
        ///
        /// \param  message         The error message that explains the reason for the exception.
        /// \param  innerException  The exception that is the cause of the current exception, or a null
        ///                         reference (Nothing in Visual Basic) if no inner exception is
        ///                         specified.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Initializes a new instance of the TelEnvyXmlLib.Exceptions.TelEnvyExceptionBase
        ///             class.
        ///             </summary>
        ///
        /// <remarks>   Timothy Peer, eNVy Systems Inc., 6/26/2019. </remarks>
        ///
        /// <param name="message">          The message.</param>
        /// <param name="innerException">   The inner exception.</param>
        ///-------------------------------------------------------------------------------------------------

        public TelEnvyExceptionBase(string message, Exception innerException)
            : base(message, innerException)
        {
            
        }

        #region Documentation
        /// Gets or sets the message text.
        ///
        /// \returns    The message text.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets or sets the message text. </summary>
        ///
        /// <value> The message text. </value>
        ///-------------------------------------------------------------------------------------------------

        public string MessageText { get; set; }

        #region Documentation
        /// Gets or sets the message identifier.
        ///
        /// \returns    The message identifier.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets or sets the identifier of the message. </summary>
        ///
        /// <value> The identifier of the message. </value>
        ///-------------------------------------------------------------------------------------------------

        public string MessageId { get; set; }

        #region Documentation
        /// Gets or sets the type of the message.
        ///
        /// \returns    The type of the message.
        #endregion

        ///-------------------------------------------------------------------------------------------------
        /// <summary>   Gets or sets the type of the message. </summary>
        ///
        /// <value> The type of the message. </value>
        ///-------------------------------------------------------------------------------------------------

        public string MessageType { get; set; }
        /* •—————————————————————————————————————————————————————————————————————————————————————•
           | /// <summary>                                                                       |
           | /// Gets the message details as XML.                                                |
           | /// </summary>                                                                      |
           | /// <returns>System.String.</returns>                                               |
           | /// <autogeneratedoc />                                                             |
           | /// TODO Edit XML Comment Template for getMessageDetailsAsXML                       |
           | public string  getMessageDetailsAsXML()                                             |
           | {                                                                                   |
           |     StringBuilder sbx = new StringBuilder();                                        |
           |     sbx.AppendLine("<MessageDetails>");                                             |
           |     sbx.AppendLine(string.Format("  <Message>{0}</Message>",Message));              |
           |     sbx.AppendLine(string.Format("  <MessageId>{0}</MessageId>", MessageId));       |
           |     sbx.AppendLine(string.Format("  <MessageType>{0}</MessageType>", MessageType)); |
           |     sbx.AppendLine("</MessageDetails>");                                            |
           |     return sbx.ToString();                                                          |
           | }                                                                                   |
           •—————————————————————————————————————————————————————————————————————————————————————• */
        /* •———————————————————————————————————————————————————————————————————————————————————————•
           | /// <summary>                                                                         |
           | /// To the message details as XML.                                                    |
           | /// </summary>                                                                        |
           | /// <returns>System.String.</returns>                                                 |
           | /// <autogeneratedoc />                                                               |
           | /// TODO Edit XML Comment Template for ToMessageDetailsAsXML                          |
           | //public override string ToString()                                                   |
           | //{                                                                                   |
           | //    StringBuilder sbx = new StringBuilder();                                        |
           | //    sbx.AppendLine("<MessageDetails>");                                             |
           | //    sbx.AppendLine(string.Format("  <Message>{0}</Message>", Message));             |
           | //    sbx.AppendLine(string.Format("  <MessageId>{0}</MessageId>", MessageId));       |
           | //    sbx.AppendLine(string.Format("  <MessageType>{0}</MessageType>", MessageType)); |
           | //    sbx.AppendLine("</MessageDetails>");                                            |
           | //    return sbx.ToString();                                                          |
           | //}                                                                                   |
           •———————————————————————————————————————————————————————————————————————————————————————• */

         #region Documentation
         /// TODO Edit XML Comment Template for MessageDetails
         ///
         /// \returns   The message details.
         #endregion

         ///-------------------------------------------------------------------------------------------------
         /// <summary>  Gets or sets the message details. </summary>
         ///
         /// <value>    The message details. </value>
         ///-------------------------------------------------------------------------------------------------

         public MessageDetails_c MessageDetails { get; set; }

    }
}
