// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-27-2018
// ***********************************************************************
// <copyright file="FtpConnectionStatusCOMEventArgs.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace TelEnvyCOMLibrary.EventArgs
{
    //
    // Summary:
    //     Event arguments for the ConnectionStatus event.
    /// <summary>
    /// Class FtpConnectionStatusCOMEventArgs.
    /// </summary>
    /// <seealso cref="System.EventArgs" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FtpConnectionStatusCOMEventArgs
    public class FtpConnectionStatusCOMEventArgs : System.EventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FtpConnectionStatusCOMEventArgs"/> class.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public FtpConnectionStatusCOMEventArgs()
        {
            
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FtpConnectionStatusCOMEventArgs" /> class.
        /// </summary>
        /// <param name="connectionEvent">The connection event.</param>
        /// <param name="description">The description.</param>
        /// <param name="statusCode">The status code.</param>
        public FtpConnectionStatusCOMEventArgs(string connectionEvent, string description, int statusCode)
        {
            ConnectionEvent = connectionEvent;
            Description = description;
            StatusCode = statusCode;
        }
        /// <summary>
        /// Gets or sets the connection event.
        /// </summary>
        /// <value>The connection event.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ConnectionEvent
        public string ConnectionEvent { get; set; }
        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        /// <value>The description.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Description
        public string Description { get; set; }
        /// <summary>
        /// Gets or sets the status code.
        /// </summary>
        /// <value>The status code.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for StatusCode
        public int StatusCode { get; set;  }
    }
}
