// ***********************************************************************
// Assembly         : TelEnvyCOMLibrary
// Author           : Timothy Peer
// Created          : 05-27-2018
//
// Last Modified By : Timothy Peer
// Last Modified On : 05-27-2018
// ***********************************************************************
// <copyright file="FtpStartTransferCOMEventArgs.cs" company="eNVy Systems, Inc.">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;

namespace TelEnvyCOMLibrary.EventArgs
{
    //
    // Summary:
    //     Event arguments for the StartTransfer event.
    /// <summary>
    /// Class FtpStartTransferCOMEventArgs.
    /// </summary>
    /// <seealso cref="System.EventArgs" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FtpStartTransferCOMEventArgs
    public class FtpStartTransferCOMEventArgs : System.EventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FtpStartTransferCOMEventArgs" /> class.
        /// </summary>
        /// <param name="direction">The direction.</param>
        public FtpStartTransferCOMEventArgs(int direction)
        {
            Direction = direction;
        }

        /// <summary>
        /// Gets or sets the direction.
        /// </summary>
        /// <value>The direction.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Direction
        public int Direction { get; set; }
    }
}
